on:
  workflow_dispatch:

jobs:
  deploy_branch:
    runs-on: ubuntu-latest
    steps:

      - name: get input
        run: |
          echo "This is a test"
          echo "This is a test"
          echo "This is a test"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1