on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        type: string
      service:
        description: 'Service to Deploy'
        required: true
        type: string
      repo:
        description: 'the repository'
        type: string
        required: true

jobs:
  deploy_branch:
    runs-on: ubuntu-latest
    steps:

      - name: get input
        run: |
          echo "branch: $BRANCH"
          echo "service: $SERVICE"
          echo "repo: $REPO"
        env:
          BRANCH: ${{ inputs.branch }}
          SERVICE: ${{ inputs.service }}
          REPO: ${{ inputs.repo }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
         ref: ${{ github.event.ref }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1